In [2]:
import numpy as np
a=np.array([[[3,2],[5,6]],[[0,0],[1,1]]])
print(a)

[[[3 2]
  [5 6]]

 [[0 0]
  [1 1]]]


In [3]:
c=a.tolist()
print(c)

[[[3, 2], [5, 6]], [[0, 0], [1, 1]]]


In [4]:
matrice=np.array([[5,4,2,3],[2,8,9,7],[10,11,13,12],[14,15,16,17]])

In [5]:
def sumDiagonal(q2):
    d=0
    l=q2.shape
    if l[0]==l[1]:
        for i in range(0,l[0]):
            d=d+q2[i,i]
    return d

In [6]:
sumDiagonal(matrice)

43

In [7]:
def question3(q3,x):
    lis=[]
    l=q3.shape
    for i in range(0,l[0]):
        for j in range(0,l[1]):
            if q3[i,j]>x:
                lis.append(q3[i,j])
    return lis

In [9]:
a=question3(matrice,2)
print(a)

[5, 4, 3, 8, 9, 7, 10, 11, 13, 12, 14, 15, 16, 17]


In [10]:
A=np.array([[5,4,2,3],[2,8,9,7],[10,11,13,12],[14,15,16,17]])
B=np.array([[2,8,9,7],[10,3,3,15],[7,5,6,7],[5,4,2,3]])
print(A)

[[ 5  4  2  3]
 [ 2  8  9  7]
 [10 11 13 12]
 [14 15 16 17]]


In [11]:
def question4(a,b):

    if a.shape==b.shape:
        l=a.shape
        c=np.zeros(l)
        for i in range(0,l[0]):
            for j in range(0,l[1]):
                c[i,j]=a[i,j]+b[i,j]
    else:
        print("impossible")
    return c


In [12]:
question4(A,B)

array([[ 7., 12., 11., 10.],
       [12., 11., 12., 22.],
       [17., 16., 19., 19.],
       [19., 19., 18., 20.]])

In [13]:
import statistics
def question5(a):
    l=a.shape
    c=a
    for i in range(0,l[0]):
        m=statistics.mean(a[i,:])
        for j in range(0,l[1]):
            c[i,j]=c[i,j]-m
    return c

In [14]:
question5(A)

array([[ 2,  1, -1,  0],
       [-4,  2,  3,  1],
       [-1,  0,  2,  1],
       [-1,  0,  1,  2]])